apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mjchp46um-python 
  janus-idp.io/tekton: mjchp46um-python
  backstage.io/kubernetes-id: mjchp46um-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mjchp46um-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  